apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: strongNotAdmin
    namespace: test1
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - deployments
    verbs:
    - create
    - watch
   
  
