# This file was generated by GoReleaser. DO NOT EDIT.
class Kubecli < Formula
  desc "kubecli --help"
  homepage "http://docs.codefresh.io"
  url "https://github.com/verchol/kubecli/releases/download/v1.0.3/kubecli_1.0.3_Darwin_x86_64.tar.gz"
  version "1.0.3"
  sha256 "4ea2eb1e1c0152c53a00f7f015a6b1631f3f11a54c9937dc758e8c51ce800fad"

  def install
    bin.install "kubecli"
  end
end
