name: Go
on: [push]
jobs:
  init:
   runs-on: ubuntu-latest
   steps:
     - run : ls -lt
     - run : env .
  build:
    name: Build
    runs-on: ubuntu-latest
    #env:
     # working-directory: $GITHUB_WORKSPACE
    container:  
     image: goreleaser/goreleaser:v0.138
    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: GoReleaser Action
      run: ls -lt  && goreleaser --version && cat .goreleaser.yml 
    - run: goreleaser build --snapshot
       
  build1:
    name: Build1
    runs-on: ubuntu-latest
    #env:
     # working-directory: $GITHUB_WORKSPACE
    container:  
     image: goreleaser/goreleaser:v0.137
    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: GoReleaser Action
      run: ls -lt  && goreleaser --version && cat .goreleaser.yml 
    - run: goreleaser build --snapshot
