name: Go
on: [push]
# comment
jobs:
  init:
   runs-on: ubuntu-latest
   container:  
     image: alpine
   steps:
     - run : ls -lt
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Run GoReleaser Action
      uses: goreleaser/goreleaser-action@v2
      with:
          version: latest
          args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
  build1:
    name: Build1
    runs-on: ubuntu-latest
    container:  
     image: goreleaser/goreleaser:v0.137
    steps:
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
          version: latest
          args: release --rm-dist
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
       
