name: Go
on: [push]
jobs:
  init:
   runs-on: ubuntu-latest
   container:  
     image: alpine
   steps:
     - run : ls -lt
  build:
    name: Build
    runs-on: ubuntu-latest
    #env:
     # working-directory: $GITHUB_WORKSPACE
    #container:  
     #image: goreleaser/goreleaser:v0.138
    steps:
    - name: checkout 
      uses: actions/checkout@v2
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: compile and release
      uses: ngs/go-release.action@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
       
