name: Go
on: [push]
jobs:
   testing: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Git checkout"
        uses: actions/checkout@v1
      - 
        name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with: 
          node-version: "${{ matrix.node-version }}"
      - 
        name: "Start MongoDB v${{ matrix.node-version }}"
        uses: superchargejs/mongodb-github-action@1.0.0
        with: 
          mongodb-version: "${{ matrix.mongodb-version }}"
    strategy: 
      matrix: 
        mongodb-version: 
          - 4.0
          - 4.2
        node-version: 
          - 8.x
          - 10.x
          - 12.x
          - 13.x
  init:
   runs-on: ubuntu-latest
   steps:
     - run : ls -lt
     - run : env .
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v1.2.1
      with:
         workdir : ${{env.working-directory}}

